controller:
  service:
    internal:
      enabled: false
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp        # type of LB protocol, either TCP/UDP
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'   # in seconds
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'  # enable cross AWS zone LB, EX- east-1a to east-1b
      service.beta.kubernetes.io/aws-load-balancer-type: nlb                         # type of LB
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxxxxxxxxx:certificate/274d4c80-dc76-4296-b3ed-d959cbe837ba  # ARN of the SSL certificate from ACM
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443      # ports to be used for SSL 